### ISSUE TITLE
Can I get contant info of yours?

### ISSUE THREAD

**Issue by samchon** [sinclairzx81/runtime-type-benchmarks#10]
Hello, @sinclairzx81. I'm sorry for posting unrelated issue with repo, but hoped to contact with you.

I'm developer in Wrtn company, and looking for someone expert like you.

Can I get your e-mail address? It's okay to you sending me any email (samchon@wrtn.io)

**Comment by sinclairzx81** [comment]
@samchon Hi!

It's fine. If you want to send me through an email, that's ok. You can reach me at haydn.developer@gmail.com.

For now, I'll close up this issue and will remove tomorrow.
Cheers!
S

**Comment by samchon** [comment]
Thank you for quick response. 

Copied your email address, so it is okay to delete this issue fron now on.

About the job position introduction letter, I'll send it until this week's Friday.

**Comment by sinclairzx81** [comment]
All good :)
