### ISSUE TITLE
`typia` can validate Regexp

### ISSUE THREAD

**Issue by samchon** [sinclairzx81/runtime-type-benchmarks#5]
https://github.com/samchon/typia/wiki/Runtime-Validators#comment-tags

It is possible like below:

```typescript
export interface ISomething {
    /**
     * Mobile number composed by only numbers.
     * 
     * Note that, `typia` does not support flag of regex,
     * because JSON schema definition does not support it either.
     * Therefore, write regex pattern without `/` characters and flag.
     * 
     * @pattern ^0[0-9]{7,16} 
     *     -> RegExp(/[0-9]{7,16}/).test("01012345678")
     */
    mobile: string;
}
```

**Comment by sinclairzx81** [comment]
@samchon Heya,

Yeah, I tried to get that working, but typia refused to generate a `RegExp` object in the output. I probably won't have much time to figure out why, but if you want to have a go adding it, PR's are welcome. I've left a section commented there to write the `@pattern ^0[0-9]{7,16}` comment somewhere in generated output (to be reference in the `Typia.is<RegexInterface>` call for the regular expression test.

#### Code to Update

Will need to write some `interface` / `type` matching the expected regular expression as well as adding a `if` block to render the benchmark.

https://github.com/sinclairzx81/runtime-type-benchmarks/blob/dataset/benchmark/validators/typia/build.ts#L31-L37

Will also need to remove the filter on this line

https://github.com/sinclairzx81/runtime-type-benchmarks/blob/dataset/benchmark/validators/typia/build.ts#L13

#### Primitive_Regex

The `Primitive_Regex` type can be found https://github.com/sinclairzx81/runtime-type-benchmarks/blob/dataset/benchmark/schematics/primitive/RegEx.ts

```typescript
// so basically just the following
const regex = /hello/
```
Will leave this issue open for a few days.
Cheers!
S

**Comment by samchon** [comment]
Ah, you made DTO through `typebox`.

The regexp only be generated by coment tags like below:

### TypeScript
```typescript
import { is } from "typia";

export interface ISomething {
    /**
     * Mobile number composed by only numbers.
     * 
     * Note that, `typia` does not support flag of regex,
     * because JSON schema definition does not support it either.
     * Therefore, write regex pattern without `/` characters and flag.
     * 
     * @pattern ^0[0-9]{7,16}
     */
    mobile: string;
}
is<ISomething>(null!);
```

### JavaScript
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const typia_1 = require("typia");
(input => {
    const $io0 = input => 
        "string" === typeof input.mobile && 
        true === RegExp(/^0[0-9]{7,16}/).test(input.mobile);
    return "object" === typeof input && 
        null !== input && 
        (
            "string" === typeof input.mobile && 
            true === RegExp(/^0[0-9]{7,16}/).test(input.mobile)
        );
})(null);
```

**Comment by samchon** [comment]
Also, you are comparing `ts-runtime-checks`, but it can't validate most cases.

  - cannot compile recursive type
  - cannot detect not-a-number value
  - cannnot understand nullable object

What about adapting `typescript-is` instead?

It is the most famous validator in typescript transformer

https://github.com/woutervh-/typescript-is

**Comment by sinclairzx81** [comment]
@samchon `typescript-is` has been added to the test suite.

**Comment by sinclairzx81** [comment]
@samchon Fyi, Have implemented a few other schematics. Specifically tests for numeric `NaN` (which Typia doesn't seem to implement) as well as numeric range constraints, string length constraints. Have also included the TypeBox Typia schematics as well as setup Zod for testing.

[Latest Benchmark Results](https://sinclairzx81.github.io/runtime-type-benchmarks/)

I can't seem to get Typia to emit for the `String_Pattern` benchmark. But Ideally I just want the following to work.

```typescript
/** @pattern 1234567890 */
type String_Pattern = string

...

Cases.Benchmark(Cases.String_Pattern, iterations, results, () => (value) => Typia.is<String_Pattern>(value))
```

However, looking at the Typia documentation, it appears the it supports numeric constraints (as comments). Would you be interested in submitting a PR for the regex, numeric and string constraints?

**Comment by samchon** [comment]
Comment tags like the pattern works only on property. Haven't thought about the atomic case.

**Comment by sinclairzx81** [comment]
@samchon I couldn't get this to work either.

```typescript
interface Inline {
   /** @pattern 1234567890 */
   String_Pattern: string
}
...

Cases.Benchmark(Cases.String_Pattern, iterations, results, () => (value) => Typia.is<Inline['String_Pattern']>(value))
```

**Comment by samchon** [comment]
It works only when validating `Inline` type yet.

**Comment by sinclairzx81** [comment]
Alright, will leave this issue open and revisit when `typia` supports the inline comment constraints. 

Keep me posted.

**Comment by samchon** [comment]
Tested but not possible in current architecture of `typia` utilizing `ts.Type`.

**Comment by sinclairzx81** [comment]
@samchon Heya,

I've updated the typia benchmark to include Integer (you can copy and paste this and amend for Regex)

```typescript
import { Formatter } from '../../../codegen/index'
import { TypeGuard, TSchema } from '@sinclair/typebox'
import * as Cases from '../../schematics/correct'
import * as Fs from 'node:fs'
import * as Path from 'node:path'

export namespace TypiaGenerator {
  function Include(schema: unknown): schema is TSchema {
    return (
      TypeGuard.TSchema(schema) &&
      ![
        'Number_NaN',
        'Number_Exclusive_Maximum',
        'Number_Exclusive_Minimum',
        'Number_Maximum',
        'Number_Minimum',
        'Number_Multiple_Of',
        'String_Pattern',
        'String_MaxLength',
        'String_MinLength',
        'Object_Additional_Properties_Boolean',
        'Typia_Ultimate_Union', // fail: on inference
      ].includes(schema.$id!)
    )
  }
  function* GenerateBenchmark(dataset: string) {
    yield `import Typia, { tags } from 'typia'`
    yield `import { Command } from '../../command/index'`
    yield `import * as Cases from '../../schematics/${dataset}'`
    yield ``
    // -------------------------------------------------------------------------------------------------------------
    // Dependent Types
    // -------------------------------------------------------------------------------------------------------------
    yield `export type Integer = tags.TagBase<{`
    yield `target: "number";`
    yield `  kind: "type";`
    yield `  value: "uint32";`
    yield `  validate: "Number.isInteger($input)"`
    yield `}>;`
    // -------------------------------------------------------------------------------------------------------------
    // Benchmarks
    // -------------------------------------------------------------------------------------------------------------
    yield `export function Execute(iterations: number) {`
    yield `const results = new Map<string, number>()`
    for (const schema of Object.values(Cases)) {
      if (!Include(schema)) continue
      // Integer
      if(TypeGuard.TInteger(schema)) {
        yield `Cases.Benchmark(Cases.${schema.$id}, iterations, results, () => (value) => Typia.is<number & Integer>(value))`
        continue
      }
      // Object_RTTB_Strict
      if(schema.$id === 'Object_RTTB_Strict') {
        yield `Cases.Benchmark(Cases.${schema.$id}, iterations, results, () => (value) => Typia.equals<Cases.${schema.$id}>(value))`
        continue
      }
      // Object_Additional_Properties_False
      if(schema.$id === 'Object_Additional_Properties_False') {
        yield `Cases.Benchmark(Cases.${schema.$id}, iterations, results, () => (value) => Typia.equals<Cases.${schema.$id}>(value))`
        continue
      }
      // Standard Type
      yield `Cases.Benchmark(Cases.${schema.$id}, iterations, results, () => (value) => Typia.is<Cases.${schema.$id}>(value))`
    }
    yield `return results`
    yield `}`
    yield ``
    yield `const parameter = Command.Parameter()`
    yield `const results = Execute(parameter.iterations)`
    yield `Command.WriteResults(results)`
  }
  function Generate(directory: string, dataset: string) {
    const output = Formatter.Format([...GenerateBenchmark(dataset)].join('\n'))
    const filename = Path.join(directory, dataset) + '.ts'
    Fs.writeFileSync(filename, output, 'utf-8')
  }
  export function Build(directory: string) {
    Fs.mkdirSync(directory, { recursive: true })
    Generate(directory, 'correct')
    Generate(directory, 'incorrect')
  }
}
```
To build and run, use the following command.
```bash
$ hammer task typia
```
I have tried running typia 5.0.1 this against both TS 4.9.5 and TS 5.2.2 and but presented with the following error.
```
package: typia dataset: correct iterations: 10000000
...\runtime-type-benchmarks\node_modules\ttypescript\lib\patchCreateProgram.js:84
    tsm.createProgram = createProgram;
                      ^

TypeError: Cannot set property createProgram of #<Object> which has only a getter
    at patchCreateProgram
```
The task to run the typia benchmark can be found at here.

https://github.com/sinclairzx81/runtime-type-benchmarks/blob/main/hammer.mjs#L51C17-L52

This project may need updates to the `hammer.mjs` (and package.json) to support the varying AOT builds (the benchmarks are only current as of the beginning of the year, and I've not had a lot of time to maintain them). But feel free to modify the tasks as necessary to get typia building.

**Comment by sinclairzx81** [comment]
@samchon This project may be updated to use https://github.com/sinclairzx81/typebox-codegen in later revisions (as the code generation developed for this project has been more refined on `typebox-codegen`). However the AOT solutions tend to be somewhat complicated to manage given configuration overlap, changes to compiler infrastructure (`ts-patch`) and other factors.

But I'll try look into updating the benchmarks at the end of the year (as I think once a year updates reviewing the state of performance are better than a tracking incremental updates per validator during the year), also I've limited time to invest in this project at this time, but will see about updating late November / December (but happy to accept PR's and enhancements to the current testing infrastructure (which admittingly, is very complex))

Cheers
S

**Comment by samchon** [comment]
Is there any special reason that generating TS codes from string concat?

**Comment by sinclairzx81** [comment]
@samchon yes, simplicity
